#!/usr/bin/env python3
"""Investigate CLI scaffold"""

import argparse


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Investigate incident scaffold")
    parser.add_argument("metrics_csv", help="Path to metrics CSV generated by simulator")
    parser.add_argument("--question", default="What is the most likely root cause and blast radius?")
    parser.add_argument("--top-k", type=int, default=12)
    parser.add_argument("--reindex", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print("SIREN scaffold")
    print("======================")
    print(f"metrics_csv: {args.metrics_csv}")
    print("Retrieval indexing and hybrid ranking are not implemented yet")


if __name__ == "__main__":
    main()
