#!/usr/bin/env python3
"""Investigate incident bundles and produce an RCA report"""

import argparse
import csv
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any
import re

PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from dotenv import load_dotenv
load_dotenv(PROJECT_ROOT / ".env")

from retrieval.indexer import index_incident
from retrieval.orchestrator import SirenQueryEngine
from agent.run import run_investigation as _run_agent
from feedback.store import FeedbackStore
from detection import detect


ANOMALY_SERVICE_ORDER = {
    "database": 0,
    "auth-service": 1,
    "payment-service": 2,
    "recommendation-service": 3,
    "api-gateway": 4,
    "cache": 5,
    "message-queue": 6,
}


def _resolve_bundle_paths(metrics_csv: Path) -> tuple[Path, Path, Path, Path, str]:
    metrics_path = metrics_csv.resolve()
    bundle_root = metrics_path.parent.parent
    logs_path = bundle_root / "logs" / metrics_path.name
    traces_path = bundle_root / "traces" / metrics_path.name
    docs_path = bundle_root.parent / "docs"

    match = re.match(r"^(?P<incident>.+)_(?P<timestamp>\d{4}-\d{2}-\d{2}_\d{2}:\d{2})$", metrics_path.stem)
    incident_name = match.group("incident") if match else metrics_path.stem

    return metrics_path, logs_path, traces_path, docs_path, incident_name


def _coerce_metric_value(key: str, value: str) -> Any:
    if key in {"timestamp", "service", "instance"}:
        return value
    if value in (None, ""):
        return value
    try:
        return float(value)
    except ValueError:
        return value


def _load_metrics(metrics_csv: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with metrics_csv.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows.append({key: _coerce_metric_value(key, value) for key, value in row.items()})
    return rows


def _derive_anomaly_window(anomalies: list[dict[str, Any]]) -> tuple[str, str, str]:
    if not anomalies:
        raise ValueError("No anomalies were detected in the metrics file")

    ordered = sorted(
        anomalies,
        key=lambda anomaly: (anomaly["timestamp"], ANOMALY_SERVICE_ORDER.get(anomaly["service"], 99)),
    )
    origin_service = ordered[0]["service"]
    earliest = datetime.fromisoformat(ordered[0]["timestamp"])
    latest = datetime.fromisoformat(ordered[-1]["timestamp"])
    window_start = (earliest - timedelta(minutes=5)).isoformat()
    window_end = (latest + timedelta(minutes=5)).isoformat()
    return origin_service, window_start, window_end


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Investigate an incident bundle")
    parser.add_argument("metrics_csv", help="Path to the metrics CSV generated by the simulator")
    parser.add_argument("--reindex", action="store_true", help="Force reindexing the bundle")
    return parser.parse_args()


def run_investigation(
    metrics_csv: str | Path,
    reindex: bool = True,
) -> dict[str, Any]:
    metrics_path, logs_path, traces_path, docs_path, incident_name = _resolve_bundle_paths(Path(metrics_csv))

    if not metrics_path.exists():
        raise FileNotFoundError(f"Metrics CSV not found: {metrics_path}")
    if not logs_path.exists():
        raise FileNotFoundError(f"Logs CSV not found: {logs_path}")
    if not traces_path.exists():
        traces_path = None
    if not docs_path.exists():
        raise FileNotFoundError(f"Docs directory not found: {docs_path}")

    metrics = _load_metrics(metrics_path)
    anomalies, incident = detect(metrics)
    incident_type = incident.get("anomaly_type", "compute")
    origin_service, window_start, window_end = _derive_anomaly_window(anomalies)
    incident_id = incident_name

    try:
        engine = SirenQueryEngine()
    except Exception as exc:
        raise RuntimeError(
            "Failed to initialize the retrieval engine. Set the Pinecone, OpenAI, Cohere, Neo4j, TimescaleDB, and Redis environment variables, and ensure the backing services are running"
        ) from exc

    if reindex:
        index_incident(
            metrics_csv=str(metrics_path),
            logs_csv=str(logs_path),
            docs_dir=str(docs_path),
            orchestrator=engine,
            traces_csv=str(traces_path) if traces_path else None,
        )

    print(f"Starting agent investigation: {incident_id} (type: {incident_type})")
    agent_state = _run_agent(
        anomalies=anomalies,
        origin_service=origin_service,
        window_start=window_start,
        window_end=window_end,
        incident_id=incident_id,
        incident_type=incident_type,
    )

    report = agent_state.get("final_report") or ""
    timestamp = datetime.now().strftime("%Y-%m-%d_%H:%M")
    report_dir = PROJECT_ROOT / "data" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"{timestamp}_{incident_name}_agent.md"
    report_path.write_text(report, encoding="utf-8")

    try:
        feedback_store = FeedbackStore()
        feedback_store.save_investigation(agent_state, incident_type)
    except Exception as e:
        print(f"Warning: Could not save investigation to feedback store: {e}")

    return {
        "incident_id": incident_id,
        "incident_name": incident_name,
        "origin_service": origin_service,
        "anomaly_metric": str(anomalies[0]["metric"]),
        "anomalies": anomalies,
        "report": report,
        "report_path": report_path,
        "final_root_cause": agent_state.get("final_root_cause"),
        "final_confidence": agent_state.get("final_confidence"),
        "final_report": agent_state.get("final_report"),
        "current_step": agent_state.get("current_step"),
        "evidence_ledger": agent_state.get("evidence_ledger", {}),
    }


def main() -> None:
    args = parse_args()
    result = run_investigation(args.metrics_csv, reindex=args.reindex)

    print(f"\nRoot cause: {result['final_root_cause']}")
    confidence = result.get("final_confidence")
    print(f"Confidence: {confidence:.0%}" if confidence is not None else "Confidence: (unknown)")
    print(f"Steps taken: {result['current_step']}")
    print(f"\nReport saved to {result['report_path'].relative_to(PROJECT_ROOT)}")
    print("\n" + result["report"])


if __name__ == "__main__":
    main()
