#!/usr/bin/env python3
"""Investigate incident bundles and produce an RCA report"""

import argparse
import csv
import importlib
import os
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from retrieval.indexer import index_incident
from retrieval.orchestrator import SirenQueryEngine
from siren import ANOMALY_SERVICE_ORDER, detect_anomalies, local_rca_fallback

RCA_SYSTEM_PROMPT = (
    "You are Siren, an autonomous AI Site Reliability Engineer. You have been given \n"
    "telemetry data from a distributed system that is experiencing an incident. \n"
    "Your job is to analyze the evidence and produce a structured root cause analysis.\n\n"
    "Be precise and systematic. Follow the evidence - do not guess. If the dependency \n"
    "graph shows that service A calls service B, and service B degraded first, that \n"
    "is strong evidence that B is the root cause, not A."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Investigate an incident bundle")
    parser.add_argument("metrics_csv", help="Path to metrics CSV generated by simulator")
    parser.add_argument("--top-k", type=int, default=12, help="Number of retrieval candidates to use")
    parser.add_argument("--reindex", action="store_true", help="Force reindexing the incident bundle")
    return parser.parse_args()


def _resolve_bundle_paths(metrics_csv: Path) -> tuple[Path, Path, Path, Path, str]:
    metrics_path = metrics_csv.resolve()
    bundle_root = metrics_path.parent.parent
    logs_path = bundle_root / "logs" / metrics_path.name
    traces_path = bundle_root / "traces" / metrics_path.name
    docs_path = bundle_root.parent / "docs"

    match = re.match(r"^(?P<incident>.+)_(?P<timestamp>\d{4}-\d{2}-\d{2}_\d{2}:\d{2})$", metrics_path.stem)
    incident_name = match.group("incident") if match else metrics_path.stem

    return metrics_path, logs_path, traces_path, docs_path, incident_name


def _coerce_metric_value(key: str, value: str) -> Any:
    if key in {"timestamp", "service", "instance"}:
        return value
    if value in (None, ""):
        return value
    try:
        return float(value)
    except ValueError:
        return value


def _load_metrics(metrics_csv: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with metrics_csv.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows.append({key: _coerce_metric_value(key, value) for key, value in row.items()})
    return rows


def _derive_anomaly_window(anomalies: list[dict[str, Any]]) -> tuple[str, str, str]:
    if not anomalies:
        raise ValueError("No anomalies were detected in the metrics file")

    ordered = sorted(
        anomalies,
        key=lambda anomaly: (anomaly["timestamp"], ANOMALY_SERVICE_ORDER.get(anomaly["service"], 99)),
    )
    origin_service = ordered[0]["service"]
    earliest = datetime.fromisoformat(ordered[0]["timestamp"])
    latest = datetime.fromisoformat(ordered[-1]["timestamp"])
    window_start = (earliest - timedelta(minutes=5)).isoformat()
    window_end = (latest + timedelta(minutes=5)).isoformat()
    return origin_service, window_start, window_end


def _format_list(values: list[str]) -> str:
    return ", ".join(values) if values else "(none)"


def _format_metrics(metrics: dict[str, Any] | None) -> str:
    if not metrics:
        return "(none)"

    pieces: list[str] = []
    for key in ("error_rate", "latency_p99", "rps", "memory"):
        value = metrics.get(key)
        if value is not None:
            pieces.append(f"{key}={value}")
    return ", ".join(pieces) if pieces else "(none)"


def _format_retrieved_context(result: dict[str, Any], top_k: int) -> str:
    lines: list[str] = []
    lines.append("=== RETRIEVED EVIDENCE ===")
    lines.append(f"Origin service: {result.get('origin_service', '(unknown)')}")
    lines.append(f"Affected services: {_format_list(result.get('affected_services', []))}")
    lines.append(f"Blast radius: {_format_list(result.get('blast_radius', []))}")

    cascade_paths = result.get("cascade_paths", []) or []
    if cascade_paths:
        lines.append("Critical path: " + " -> ".join(cascade_paths[0]))

    lines.append("")
    lines.append("=== ANOMALIES ===")
    for anomaly in result.get("anomalies", [])[: min(5, top_k)]:
        lines.append(
            f"[{anomaly['timestamp']}] {anomaly['service']} {anomaly['metric']}="
            f"{anomaly['value']} z={anomaly['zscore']}"
        )

    lines.append("")
    lines.append("=== TOP LOGS ===")
    for item in result.get("top_logs", [])[:3]:
        lines.append(f"- {item.get('text', '')}")

    lines.append("")
    lines.append("=== TOP TRACES ===")
    for item in result.get("top_traces", [])[:3]:
        lines.append(f"- {item.get('text', '')}")

    lines.append("")
    lines.append("=== TOP DOCS ===")
    for item in result.get("top_docs", [])[:2]:
        text = str(item.get("text", ""))
        lines.append(f"- {text[:240]}")

    lines.append("")
    lines.append("=== METRICS SUMMARY ===")
    metrics_summary = result.get("metrics_summary", {}) or {}
    for service, summary in list(metrics_summary.items())[:4]:
        baseline = _format_metrics(summary.get("baseline"))
        peak = _format_metrics(summary.get("peak"))
        lines.append(f"- {service}: baseline [{baseline}] peak [{peak}]")

    return "\n".join(lines)


def _build_user_prompt(context: str) -> str:
    return (
        "Analyze the following incident telemetry and produce a Root Cause Analysis report.\n\n"
        f"{context}\n\n"
        "Respond in exactly this format:\n\n"
        "## INCIDENT SUMMARY\n"
        "One paragraph describing what happened, which services were affected, and the timeline.\n\n"
        "## ROOT CAUSE\n"
        "The single most likely root cause, stated as one clear sentence.\n\n"
        "## EVIDENCE\n"
        "3-5 bullet points of specific evidence from the telemetry that supports your root cause conclusion.\n\n"
        "## BLAST RADIUS\n"
        "Which services were directly affected vs transitively affected, and how.\n\n"
        "## CONFIDENCE\n"
        "A percentage (0-100%) reflecting how confident you are in this root cause, and one sentence explaining why.\n\n"
        "## RECOMMENDED ACTIONS\n"
        "3-5 concrete remediation steps, ordered by priority."
    )


def _call_claude(context: str) -> str:
    config = os.getenv("ANTHROPIC_API_KEY", "")
    if not config:
        return local_rca_fallback()

    anthropic_module = importlib.import_module("anthropic")
    client = anthropic_module.Anthropic(api_key=config)
    model = os.getenv("ANTHROPIC_MODEL", "claude-3-5-sonnet-latest")
    response = client.messages.create(
        model=model,
        temperature=0,
        max_tokens=1800,
        system=RCA_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": _build_user_prompt(context)}],
    )

    content = getattr(response, "content", [])
    parts: list[str] = []
    for block in content:
        text = getattr(block, "text", "")
        if text:
            parts.append(text)

    return "\n".join(parts).strip() or local_rca_fallback()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Investigate an incident bundle")
    parser.add_argument("metrics_csv", help="Path to the metrics CSV generated by the simulator")
    parser.add_argument("--top-k", type=int, default=12, help="Retrieval candidates per source")
    parser.add_argument("--reindex", action="store_true", help="Force reindexing the bundle")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    metrics_path, logs_path, traces_path, docs_path, incident_name = _resolve_bundle_paths(Path(args.metrics_csv))

    if not metrics_path.exists():
        raise FileNotFoundError(f"Metrics CSV not found: {metrics_path}")
    if not logs_path.exists():
        raise FileNotFoundError(f"Logs CSV not found: {logs_path}")
    if not traces_path.exists():
        traces_path = None
    if not docs_path.exists():
        raise FileNotFoundError(f"Docs directory not found: {docs_path}")

    metrics = _load_metrics(metrics_path)
    anomalies = detect_anomalies(metrics)
    origin_service, window_start, window_end = _derive_anomaly_window(anomalies)
    query = f"{origin_service} {anomalies[0]['metric']} anomaly cascading failure"

    try:
        engine = SirenQueryEngine()
    except Exception as exc:
        raise RuntimeError(
            "Failed to initialize the retrieval engine. Set the Pinecone, OpenAI, Cohere, Neo4j, TimescaleDB, and Redis environment variables, and ensure the backing services are running"
        ) from exc
    index_incident(
        metrics_csv=str(metrics_path),
        logs_csv=str(logs_path),
        docs_dir=str(docs_path),
        orchestrator=engine,
        traces_csv=str(traces_path) if traces_path else None,
    )

    retrieved = engine.retrieve(
        query=query,
        anomalies=anomalies,
        origin_service=origin_service,
        window_start=window_start,
        window_end=window_end,
    )
    retrieval_context = _format_retrieved_context(retrieved, args.top_k)
    report = _call_claude(retrieval_context)

    report_dir = PROJECT_ROOT / "data" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H:%M")
    report_path = report_dir / f"{timestamp}_{incident_name}.md"
    report_path.write_text(report, encoding="utf-8")

    print(report)
    print(f"\nSaved report to {report_path.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
